---
- name: nginx
  become: true
  hosts: terraform
  tasks:
  - name: install nginx
    apt:
      name:
        - nginx
      state: present
  - name: tuned activ
    shell: |
      systemctl start xginx
      systemctl enable --now nginx
  - name: test_server
    shell: systemctl status nginx
    register: command
  - debug:
      var: command.stdout_lines